server:
  port: 9095

spring:
  data:
    mongodb:
      auto-index-creation: true
      database: projecthotel

jwt:
  secret: secret
  expiration: 3600

password: 123456
#Duración de sesión -> 1 hora.
